#!/usr/bin/env python3
"""  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TL;DR  -->  install and run local git hooks for bounded frontend quality checks

- Later Extension Points:
    --> Add more hook stages here only when another owned local quality gate proves stable enough for developer workflow enforcement

- Role:
    --> Installs repo-owned local git hook wrappers into `.git/hooks`
    --> Runs fast lint checks on pre-commit and browser-smoke checks on pre-push
    --> Applies only to this repository because it writes wrappers only inside this repo's `.git/hooks` directory and never edits global git config
    --> Must stay a local-operator helper instead of becoming a second CI policy engine

- Exports:
    --> CLI entry point for hook installation and hook-stage execution

- Consumed By:
    --> local operators running `python3 tools/scripts/hooks.py install`
    --> `.git/hooks/pre-commit` and `.git/hooks/pre-push` wrappers installed by this script
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  """

from __future__ import annotations

# ---------- imports and dependencies ----------

import argparse
import os
import stat
import subprocess
import sys
from pathlib import Path

# ---------- runtime identity ----------

REPO_ROOT = Path(__file__).resolve().parents[2]
GIT_HOOKS_DIR = REPO_ROOT / '.git' / 'hooks'
GENERATED_MARKER = '# Auto-generated by tools/scripts/hooks.py'
HOOK_WRAPPERS = {
    'pre-commit': 'pre-commit',
    'pre-push': 'pre-push',
}

# ---------- subprocess helpers ----------


def run_command(command: list[str], cwd: Path) -> int:
    """Run one local hook command and mirror its output."""
    result = subprocess.run(command, cwd=cwd)
    return result.returncode


# ---------- hook installation helpers ----------


def hook_wrapper_contents(stage: str) -> str:
    """Build the local git hook wrapper for one stage."""
    return '\n'.join(
        [
            '#!/bin/sh',
            GENERATED_MARKER,
            f'exec python3 "{REPO_ROOT / "tools" / "scripts" / "hooks.py"}" {stage} "$@"',
            '',
        ]
    )


def install_wrappers() -> int:
    """Install local git hook wrappers into .git/hooks."""
    if not GIT_HOOKS_DIR.exists():
        print(f'ERROR: missing git hooks directory: {GIT_HOOKS_DIR}')
        return 1

    print(f'Installing project-local hooks in {GIT_HOOKS_DIR}')

    for file_name, stage in HOOK_WRAPPERS.items():
        hook_path = GIT_HOOKS_DIR / file_name
        if hook_path.exists():
            existing_text = hook_path.read_text(encoding='utf-8')
            if GENERATED_MARKER not in existing_text:
                print(
                    f'ERROR: refusing to overwrite non-generated hook: {hook_path.relative_to(REPO_ROOT)}. Move or merge the existing hook first.'
                )
                return 1
        hook_path.write_text(hook_wrapper_contents(stage), encoding='utf-8')
        hook_path.chmod(hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        print(f'Installed {hook_path.relative_to(REPO_ROOT)}')

    return 0


# ---------- hook stage runners ----------


def run_pre_commit() -> int:
    """Run the fast frontend lint hook."""
    print('==> pre-commit: frontend lint')
    return run_command(['bun', 'run', 'lint'], REPO_ROOT / 'apps' / 'web')


def run_pre_push() -> int:
    """Run the slower frontend browser-smoke hook."""
    print('==> pre-push: frontend smoke')
    if 'PLAYWRIGHT_BROWSER_PATH' not in os.environ and Path('/opt/homebrew/bin/chromium').exists():
        os.environ['PLAYWRIGHT_BROWSER_PATH'] = '/opt/homebrew/bin/chromium'
    return run_command(['bun', 'run', 'e2e'], REPO_ROOT / 'apps' / 'web')


# ---------- cli ----------


def build_parser() -> argparse.ArgumentParser:
    """Build the local hook CLI parser."""
    parser = argparse.ArgumentParser(description='Install or run local git hooks for frontend quality checks.')
    parser.add_argument('command', choices=('install', 'pre-commit', 'pre-push'))
    parser.add_argument('hook_args', nargs='*')
    return parser


def main() -> int:
    """Run the requested hook installation or stage command."""
    parser = build_parser()
    args = parser.parse_args()

    if args.command == 'install':
        return install_wrappers()
    if args.command == 'pre-commit':
        return run_pre_commit()
    return run_pre_push()


if __name__ == '__main__':
    sys.exit(main())
